apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-angel
  namespace: angel
spec:
  storageClassName: document
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi